version: '3'

networks:
  proxy_service_network:
    external: true

services:
  nginx:
    image: nginx:stable-alpine
    container_name: transfix-webserver
    ports:
      - "8013:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    environment:
      - VIRTUAL_HOST=weblate.ir
      - LETSENCRYPT_HOST=weblate.ir
      - LETSENCRYPT_EMAIL=imohammadd@gmail.com
    networks:
      - proxy_service_network

  php:
    image: kamerk22/laravel-alpine:latest
    container_name: transfix-app
    volumes:
      - ./:/var/www
    networks:
      - proxy_service_network